### ISSUE TITLE
Pointer : Pointer with Different Shape 

### ISSUE THREAD

**Issue by hasnentai** [GeekyAnts/GaugesFlutter#4]
Develop a Pointer which points to the current value of the `LinearGauge`

```[tasklist]
### Tasks
- [ ] Pointer with Triangle Shape.
- [ ] Pointer with Circle Shape.
- [ ] Pointer with Diamond Shape.
- [ ] Pointer with  Rectangular Shape 
- [ ] Widget Test for the Same 
- [ ] Unit Test for the Same 
```
