### ISSUE TITLE
Label : Custom Label and value for `LinearGauge`

### ISSUE THREAD

**Issue by hasnentai** [GeekyAnts/GaugesFlutter#5]
Currently, we are generating labels auto depending on `start` and `end`. With this feature, we are allowing users to pass the custom value and label.

For eg 
```dart
CustomLabel(value : 30, displayValue:"30%")
```

The above would render the label with 30% as the display value on screen and can return 30 as the value 

```[tasklist]
### Tasks
- [ ] Develop an API to allow users to pass custom labels from the `LinearGauge`.
- [ ] Unit Test for the same.
- [ ] Widget Test for the same.
```
