### ISSUE TITLE
Vertical Orientation

### ISSUE THREAD

**Issue by hasnentai** [GeekyAnts/GaugesFlutter#57]
![Image](https://user-images.githubusercontent.com/26821037/223047527-be2d86b2-ef0f-4208-bc9d-afce44773178.png)

```[tasklist]
### Tasks
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/73
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/74
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/75
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/71
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/76
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/77
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/78
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/79
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/72
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/86
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/87
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/88
```
