### ISSUE TITLE
Rulers : Allow Margin from Top and Bottom for Rulers

### ISSUE THREAD

**Issue by hasnentai** [GeekyAnts/GaugesFlutter#6]
```[tasklist]
### Tasks
- [ ] Develop an API which will allow users to add margin to rulers in both modes when `rulersOnTop` is `true` or `false`.
- [ ] Add a widget Test case
- [ ] Add a Unit Test case
- [ ] https://github.com/GeekyAnts/GaugesFlutter/issues/3
```
